flags: {}
extra-package-dbs: []
packages:
- '.'
- location:
    git: https://github.com/fros1y/hfov
    commit: 7ffe43787401c363f6cf3d428457bfd224c48390

extra-deps:
- DebugTraceHelpers-0.12
- SFML-2.3.2.2
- dequeue-0.1.12

resolver: lts-6.5
